version: "3.8"
services:
  db:
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    image: mysql
  web:
    build: .
    volumes:
      - .:/workspace
    ports:
      - "3000:3000"
    depends_on:
      - db
